<Issue id="17046" key="FAB-4130" number="4130" project="10002" reporter="shimos" assignee="shimos" creator="shimos" type="10004" summary="peer node status/stop do not report errors" priority="3" resolution="10000" status="6" created="2017-05-23 23:30:42.0" updated="2018-07-20 14:12:56.0" resolutiondate="2017-06-05 14:29:25.0" votes="0" watches="1" workflowId="38656" security="10001"> <description><! CDATA “peer node status” and “peer node stop” do not show error messages but leave the exit status successful (zero) when they encounter an error. They should be fixed because this behavior would make automation or scripting difficult.  (node stop case) $ rm /var/hyperledger/production/peer.pid $ peer node stop; echo Exit Code: $? …(snip)… 2017-05-23 22:58:55.240 UTC  nodeCmd  stop -> INFO 003 Error trying to connect to local peer: grpc: timed out when dialing 2017-05-23 22:58:55.240 UTC  nodeCmd  stop -> INFO 004 Stopping local peer using process pid from /var/hyperledger/production/peer.pid 2017-05-23 22:58:55.240 UTC  main  main -> INFO 005 Exiting..... Exit Code: 0 (It should say that it could not read the pid file)  (node status case) $ peer node status; echo Exit Code: $? …(snip)… 2017-05-23 22:55:59.065 UTC  nodeCmd  status -> WARN 003 PER:404 - Error trying to connect to local peer /opt/go/src/github.com/hyperledger/fabric/peer/common/common.go:88 github.com/hyperledger/fabric/peer/common.GetAdminClient /opt/go/src/github.com/hyperledger/fabric/peer/node/status.go:44 github.com/hyperledger/fabric/peer/node.status /opt/go/src/github.com/hyperledger/fabric/peer/node/status.go:39 github.com/hyperledger/fabric/peer/node.glob..func2 /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:605 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute /opt/go/src/github.com/hyperledger/fabric/peer/main.go:119 main.main /usr/local/go/src/runtime/proc.go:192 runtime.main /usr/local/go/src/runtime/asm_amd64.s:2087 runtime.goexit Caused by: grpc: timed out when dialing status:UNKNOWN 2017-05-23 22:55:59.065 UTC  main  main -> INFO 004 Exiting..... Exit Code: 0 (The error message only appears in the log)  (channel list case: expected behavior) $ build/bin/peer channel list; echo Exit Code: $? …(snip)…. Error: Error getting endorser client channel: PER:404 - Error trying to connect to local peer /opt/go/src/github.com/hyperledger/fabric/peer/common/common.go:77 github.com/hyperledger/fabric/peer/common.GetEndorserClient /opt/go/src/github.com/hyperledger/fabric/peer/channel/channel.go:111 github.com/hyperledger/fabric/peer/channel.InitCmdFactory /opt/go/src/github.com/hyperledger/fabric/peer/channel/list.go:94 github.com/hyperledger/fabric/peer/channel.list /opt/go/src/github.com/hyperledger/fabric/peer/channel/list.go:86 github.com/hyperledger/fabric/peer/channel.listCmd.func1 /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC /opt/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute /opt/go/src/github.com/hyperledger/fabric/peer/main.go:118 main.main /usr/local/go/src/runtime/proc.go:192 runtime.main /usr/local/go/src/runtime/asm_amd64.s:2087 runtime.goexit Caused by: grpc: timed out when dialing Usage: peer channel list  flags   Flags: -h, --help   help for list …(snip)… Exit Code: 1   ></description> </Issue>
