<Issue id="32053" key="FABN-1371" number="1371" project="10604" reporter="davidkel" assignee="davidkel" creator="davidkel" type="10004" summary="fabric node sdk doesn&apos;t handle errors returned from chaincode correctly" priority="1" resolution="10000" status="6" created="2018-07-19 07:47:02.0" updated="2019-08-28 19:20:06.0" resolutiondate="2018-07-20 16:33:10.0" votes="0" watches="2" workflowId="43313"> <description><! CDATA In fabric 1.1 grpc returned chaincode errors back to the node sdk in the form {code:java}   { Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED) at new createStatusError (/Users/dave/temp/node_modules/grpc/src/client.js:64:15) at /Users/dave/temp/node_modules/grpc/src/client.js:583:15 code: 2, metadata: Metadata { _internal_repr: {} }, details: 'error executing chaincode: transaction returned with failure: Error: The current identity, with the name \'admin\' and the identifier \'01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2\', must be activated (ACTIVATION_REQUIRED)' }   {code} ie as a javascript Error object, however something has changed server side in 1.2 (as grpc version has not changed client side) and now a chaincode error is returned in the form {code:java}   { version: 0, timestamp: null, response: { status: 500, message: 'transaction returned with failure: Error: The current identity, with the name and the identifier , must be activated (ACTIVATION_REQUIRED)', payload: <Buffer > }, payload: <Buffer >, endorsement: null }  {code} Unfortunately the node-sdk doesn't take this into account and so doesn't correctly return errors back to the client application  Â   ></description> </Issue>
