<Issue id="31647" key="INDY-1449" number="1449" project="10303" reporter="vladimirwork" creator="vladimirwork" type="10004" summary="Nsreplay tool throws error on run" priority="3" status="10200" created="2018-07-04 08:28:04.0" updated="2018-10-09 10:00:03.0" votes="0" watches="3" workflowId="31661"> <description><! CDATA Build Info: indy-node 1.4.487  Steps to Reproduce: 1. Install the pool. 2. Set `STACK_COMPANION = 1` in `/etc/indy/plenum_config.py` on all nodes. 3. Restart indy-node service on all nodes. 4. Run some cases/experiments against this pool. 5. Stop indy-node service on any node. 6. Run `nscapture` or `sudo nscapture` to get archive. 7. Run `nsreplay` or `sudo nsreplay` in the same folder to replay archive.  Actual Results: {noformat} Traceback (most recent call last): File "/usr/local/bin/nsreplay", line 36, in <module> from indy_node.server.config_helper import create_config_dirs File "/usr/local/lib/python3.5/dist-packages/indy_node/server/config_helper.py", line 3, in <module> from indy_node.general_config import general_config ImportError: cannot import name 'general_config' {noformat}  Expected Results: Captured node state should be replayed without any errors.  ></description> </Issue>
