<Issue id="28808" key="FAB-9087" number="9087" project="10002" reporter="sykesm" assignee="yacovm" creator="sykesm" type="10002" summary="TestOrderingServiceSetupFailure fails intermittently" priority="3" resolution="10000" status="6" created="2018-03-23 19:13:07.0" updated="2019-03-19 10:57:28.0" resolutiondate="2018-04-22 11:45:13.0" votes="0" watches="2" workflowId="41614"> <description><! CDATA In recent builds, I've been encountering the following flake quite regularly: {code:java} 2018-03-23 14:42:02.675 EDT  deliveryClient  try -> WARN 00e Got error: Setup failed , at 1 attempt. Retrying in 0s --- FAIL: TestOrderingServiceSetupFailure (0.00s)         Error Trace:    client_test.go:230 Error:      Not equal:              expected: 0             actual  : 1 Test:       TestOrderingServiceSetupFailure 2018-03-23 14:42:02.676 EDT  deliveryClient  try -> WARN 00f Got error: Failed Recv , at 1 attempt. Retrying in 0s{code} Another common flake: {code:java} unit-tests_1  | --- FAIL: TestNewConnection (0.02s)                                                                                                                                   unit-tests_1  |     --- FAIL: TestNewConnection/client_TLS_/_server_TLS_match (10.00s)                                                                                                unit-tests_1  |         client_test.go:273: starting server with TLS                                                                                                                  unit-tests_1  |         client_test.go:282: server: accepted from 127.0.0.1:38498                                                                                                     unit-tests_1  |         client_test.go:286: tls handshake error: tls: first record does not look like a TLS handshake                                                                         Error Trace:    client_test.go:297                                                                                                                                            unit-tesError:          Received unexpected error:                                                                                                                                    unit-tes                context deadline exceeded                                                                                                                                     unit-tes                github.com/hyperledger/fabric/core/comm.(*GRPCClient).NewConnection                                                                                           unit-tes                        github.com/hyperledger/fabric/core/comm/_test/_obj_test/client.go:191                                                                                 unit-tes                github.com/hyperledger/fabric/core/comm_test.TestNewConnection.func1                                                                                          unit-tes                        /opt/gopath/src/github.com/hyperledger/fabric/core/comm/client_test.go:294                                                                            unit-tes                testing.tRunner                                                                                                                                               unit-tes                        /opt/go/src/testing/testing.go:746                                                                                                                    unit-tes                runtime.goexit                                                                                                                                                unit-tes                        /opt/go/src/runtime/asm_amd64.s:2337                                                                                                                  unit-tes                failed to create new connection                                                                                                                               unit-tesTest:           TestNewConnection/client_TLS_/_server_TLS_match                                                                                                                       Error Trace:    client_test.go:298                                                                                                                                            unit-tesError:          Expected value not to be nil.                                                                                                                                 unit-tesTest:           TestNewConnection/client_TLS_/_server_TLS_match                                                                                                               unit-tests_1  | FAIL{code}    ></description> </Issue>
