<Action id="57796" issue="38098" author="btl5037" type="comment" created="2019-03-02 02:19:08.0" updateauthor="btl5037" updated="2019-03-02 02:19:08.0"> <body><! CDATA Bumped into this here, and several other times today:  https://jenkins.hyperledger.org/job/fabric-verify-unit-tests-x86_64/9724/consoleFull   Not very difficult to replicate, focusing the test and running it several times in a row almost always will reproduce  ></body> </Action>
<Action id="58769" issue="38098" author="yacovm" type="comment" body="I think I fixed it in https://gerrit.hyperledger.org/r/#/c/29961/ ... closing in the meantime " created="2019-04-01 08:07:21.0" updateauthor="yacovm" updated="2019-04-01 08:07:21.0"/>
<Action id="66705" issue="38098" author="manish-sethi" type="comment" created="2020-01-15 15:55:05.0" updateauthor="manish-sethi" updated="2020-01-15 15:55:34.0"> <body><! CDATA Opening this Jira again...  Hit again in CI merge job with the following trace   ( https://dev.azure.com/Hyperledger/0227bd2c-c4f6-478f-be00-ee519f115180/_apis/build/builds/5368/logs/9 ) {noformat} panic: runtime error: index out of range  0  with length 0  recovered  	panic: runtime error: index out of range  0  with length 0  goroutine 1245  running : testing.tRunner.func1(0xc00016c800) 	/opt/hostedtoolcache/go/1.13.4/x64/src/testing/testing.go:874 +0x69f panic(0x115fe60, 0xc0012b0180) 	/opt/hostedtoolcache/go/1.13.4/x64/src/runtime/panic.go:679 +0x1b2 github.com/hyperledger/fabric/common/metrics/metricsfakes.(*Histogram).WithArgsForCall(0xc0000c3a48, 0x0, 0x0, 0x0, 0x0) 	/home/vsts/work/1/go/src/github.com/hyperledger/fabric/common/metrics/metricsfakes/histogram.go:95 +0x139 github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func5(0xc0000f6b00, 0xc0000f7080, 0xc0000c3500) 	/home/vsts/work/1/go/src/github.com/hyperledger/fabric/orderer/common/cluster/comm_test.go:1208 +0xdc github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func7(0xc00016c800) 	/home/vsts/work/1/go/src/github.com/hyperledger/fabric/orderer/common/cluster/comm_test.go:1276 +0x611 testing.tRunner(0xc00016c800, 0xc0003183d0) 	/opt/hostedtoolcache/go/1.13.4/x64/src/testing/testing.go:909 +0x19a created by testing.(*T).Run 	/opt/hostedtoolcache/go/1.13.4/x64/src/testing/testing.go:960 +0x652 FAIL	github.com/hyperledger/fabric/orderer/common/cluster	16.753s {noformat}    ></body> </Action>
<Action id="68534" issue="38098" author="tsharris" type="comment" body="Reopening, I attached logs from recent occurrence. " created="2020-03-24 14:05:13.0" updateauthor="tsharris" updated="2020-03-24 14:05:13.0"/>
<Action id="68543" issue="38098" author="sykesm" type="comment" body="This is the same as FAB-17593." created="2020-03-24 14:46:31.0" updateauthor="sykesm" updated="2020-03-24 14:46:31.0"/>
