<Action id="68117" issue="44410" author="sykesm" type="comment" created="2020-02-26 16:11:05.0" updateauthor="sykesm" updated="2020-02-26 16:11:05.0"> <body><! CDATA Hit it again today.  https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=8570&view=logs&j=17737827-9315-5d9e-c14a-16a17e90ef50&t=4c34d36c-6bff-5a33-cfcd-b209c5bac4c3&l=5407   ^pvtdata-fail.txt    ></body> </Action>
<Action id="68150" issue="44410" author="btl5037" type="comment" created="2020-02-27 22:52:25.0" updateauthor="btl5037" updated="2020-02-27 22:52:25.0"> <body><! CDATA And again:   https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=8809&view=logs&j=17737827-9315-5d9e-c14a-16a17e90ef50&t=4c34d36c-6bff-5a33-cfcd-b209c5bac4c3&l=5381   ></body> </Action>
<Action id="68165" issue="44410" author="denyeart" type="comment" created="2020-02-29 02:12:35.0" updateauthor="denyeart" updated="2020-02-29 02:12:35.0"> <body><! CDATA And again:  https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=8961&view=logs&jobId=7e1dd684-043b-58f9-3f54-f4b0baeb1973&j=7e1dd684-043b-58f9-3f54-f4b0baeb1973&t=83158a86-181c-5d3d-be25-1c6af30d94c1  ></body> </Action>
<Action id="68166" issue="44410" author="denyeart" type="comment" body=" ~wenjian  I&apos;ll move this to the top of the backlog..." created="2020-02-29 02:13:15.0" updateauthor="denyeart" updated="2020-02-29 02:13:15.0"/>
<Action id="68185" issue="44410" author="wenjian" type="comment" created="2020-03-02 18:29:40.0" updateauthor="wenjian" updated="2020-03-02 19:19:35.0"> <body><! CDATA Looking at the failure logs, they had the following warning:  {quote} Org1.peer1  2020-02-26 15:27:49.876 UTC  gossip.privdata  prepareBlockPvtdata -> WARN Could not fetch all missing eligible collection private write sets for block  9 . Will commit block with missing private write sets: txID: cbb8e2619f6288a081839eb5fb0fdcbc1b98968906936034e7888f9f503dfc5f, seq: 0, namespace: kvexecutor, collection: _implicit_org_Org1MSP, hash: 180c138820afb9dfc411a97955bfdd8a63059e829472ff96005bee17060ec9cd{quote}  It means that *Org1.peer1* didn't receive the pvtdata disseminated from *Org1.peer0* when committing the tx. Root cause: * current test doesn't wait for ack, so peer0 will return from endorsement w/o waiting for peer1 receiving the pvtdata. As a result, peer1 may or may not receive the disseminated pvtdata at the time of query (depending on which is done first, commit+query vs. dissemination).  Fix: change requiredPeerCount=1 so that pvtdata dissemination during endorsement will wait for the other peer's ack.    ></body> </Action>
<Action id="68187" issue="44410" author="wenjian" type="comment" body="PR: https://github.com/hyperledger/fabric/pull/778/files" created="2020-03-02 19:28:30.0" updateauthor="wenjian" updated="2020-03-02 19:28:30.0"/>
<Action id="68190" issue="44410" author="sykesm" type="comment" created="2020-03-02 22:04:24.0" updateauthor="sykesm" updated="2020-03-02 22:04:24.0"> <body><! CDATA  Fail  Pvtdata dissemination for implicit collection  It  disseminates pvtdata of implicit collection for the peer's own org but not implicit collection for another org  /home/vsts/work/1/go/src/github.com/hyperledger/fabric/integration/pvtdata/pvtdata_test.go:1125  Related?  https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=9068&view=logs&jobId=7e1dd684-043b-58f9-3f54-f4b0baeb1973&j=7e1dd684-043b-58f9-3f54-f4b0baeb1973&t=83158a86-181c-5d3d-be25-1c6af30d94c1  ></body> </Action>
<Action id="68191" issue="44410" author="sykesm" type="comment" created="2020-03-02 22:31:33.0" updateauthor="sykesm" updated="2020-03-02 22:31:33.0"> <body><! CDATA Pvtdata dissemination for implicit collection  It  disseminates pvtdata of implicit collection for the peer's own org but not implicit collection for another org   https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=9068&view=logs&j=4c66e10c-0fd8-5a92-dd62-668e591d0491  again  ></body> </Action>
<Action id="68192" issue="44410" author="wenjian" type="comment" body=" ~sykesm  Thank you. The last 2 flakes are the same issue. PR is ready for review:  https://github.com/hyperledger/fabric/pull/778" created="2020-03-02 22:50:39.0" updateauthor="wenjian" updated="2020-03-02 22:50:39.0"/>
<Action id="68207" issue="44410" author="wenjian" type="comment" created="2020-03-03 16:08:49.0" updateauthor="wenjian" updated="2020-03-03 16:08:49.0"> <body><! CDATA After PR 778, found another test flake for dissemination timed out, so pushed another PR https://github.com/hyperledger/fabric/pull/786 to increase timeout.   Build link and error:  https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=9080&view=logs&j=7e1dd684-043b-58f9-3f54-f4b0baeb1973  {quote}2020-03-02T23:10:31.5005306Z  91m e  35m Org1.peer0  0m  33m2020-03-02 23:10:30.728 UTC  gossip.gossip  SendByCriteria -> WARN 128 0m Failed sending to 10.1.0.4:24514 error: timed out 2020-03-02T23:10:31.5006702Z  91m e  35m Org1.peer0  0m  31m2020-03-02 23:10:30.728 UTC  gossip.privdata  func1 -> ERRO 129 0m Failed disseminating private RWSet for TxID 88a3055f05e04fcd4379958593a6d17e76b655e576a9255c3c49bc9bb07eb04e , namespace _lifecycle collection _implicit_org_Org1MSP : {"failures":{"timed out":1}}{quote}   ></body> </Action>
