<Issue id="25717" key="FAB-7446" number="7446" project="10002" reporter="sambhavdutt" assignee="adnanchoudhury" creator="sambhavdutt" type="10004" summary="fabic-test-daily-x86_64 fails due to LTE error in couchdb test" priority="2" resolution="10000" status="6" created="2017-12-13 15:50:37.0" updated="2019-03-19 11:12:53.0" resolutiondate="2018-03-28 16:38:23.0" votes="0" watches="3" workflowId="40788"> <description><! CDATA fabic-test-daily-x86_64 is failing as the following errors occur in test_FAB_3876_VaryNumKeysInEachTX  ledger_lte.perf_couchdb.test_FAB_3876_VaryNumKeysInEachTX (from pytest)  Error Message AssertionError: varyNumKeysInEachTx for CouchDB performance test failed.  logfile = open("output_VaryNumKeysInEachTx_couchdb.log", "w") returncode = subprocess.call( "./runbenchmarks.sh -f parameters_couchdb_daily_CI.sh " "varyNumKeysInEachTx", shell=True, stderr=subprocess.STDOUT, stdout=logfile, cwd=tool_directory) logfile.close() self.assertEqual(returncode, 0, msg="varyNumKeysInEachTx for CouchDB " "performance test failed. \nPlease check the logfile " >               +logfile.name +" for more details.") E       AssertionError: varyNumKeysInEachTx for CouchDB performance test failed.  E       Please check the logfile output_VaryNumKeysInEachTx_couchdb.log for more details.  ledger_lte.py:322: AssertionError  *Build Log*  https://jenkins.hyperledger.org/view/fabric-test/job/fabric-test-daily-x86_64/192/testReport/ledger_lte/perf_couchdb/test_FAB_3876_VaryNumKeysInEachTX/   ></description> </Issue>
