<Issue id="36610" key="FAB-13592" number="13592" project="10002" reporter="sambhavdutt" assignee="adnanchoudhury" creator="sambhavdutt" type="10004" summary="CouchDB tests FAB-3870, FAB-3877 failed in ledger_lte daily with Assertion error" priority="3" resolution="10204" status="6" created="2019-01-09 16:08:40.0" updated="2019-03-19 10:57:26.0" resolutiondate="2019-02-27 15:10:39.0" votes="0" watches="3" workflowId="48155"> <description><! CDATA There are two failed test cases FAB-3870, FAB-3877 in the daily lte tests, due to Assertion Error, The LTE tests started at 7:43 PM EST on 8th Jan, and took about 4 hours to complete which is the standard time for a successful LTE run.  *Intermittent:* No  *Branch:* release-1.4  *Error Snippet:*Â  {code:java} *23:30:35* =================================== FAILURES =============== *23:30:35* _____________ perf_couchdb.test_FAB_3870_VaryNumParallelTxPerChain ___  *23:30:35* self = <ledger_lte.perf_couchdb  testMethod=test_FAB_3870_VaryNumParallelTxPerChain>*23:30:35* *23:30:35*     def test_FAB_3870_VaryNumParallelTxPerChain(self):*23:30:35*         '''*23:30:35*              In this Performance test, we observe the performance (time to*23:30:35*              complete a set number of Ledger operations) of the Ledger component,*23:30:35*              with couchdb as the state database. We vary the number of parallel*23:30:35*              transactions per chain and observe the performance.*23:30:35* *23:30:35*              Passing criteria: Underlying LTE test completed successfully with*23:30:35*              exit code 0*23:30:35*             '''*23:30:35*         logfile = open("output_VaryNumParallelTxPerChain_couchdb.log", "w")*23:30:35*         returncode = subprocess.call( "./runbenchmarks.sh -f "*23:30:35*                 "parameters_couchdb_daily_CI.sh varyNumParallelTxPerChain",*23:30:35*                 shell=True, stderr=subprocess.STDOUT, stdout=logfile,*23:30:35*                 cwd=tool_directory)*23:30:35*         logfile.close()*23:30:35*         self.assertEqual(returncode, 0,*23:30:35*                 msg="VaryNumParallelTxPerChain for CouchDB performance test"*23:30:35* >               "failed. \nPlease check the logfile " +logfile.name+" for more"*23:30:35*                 " details.")*23:30:35* E   AssertionError: VaryNumParallelTxPerChain for CouchDB performance testfailed. *23:30:35* E    Please check the logfile output_VaryNumParallelTxPerChain_couchdb.log for more details.*23:30:35* *23:30:35* ledger_lte.py:217: AssertionError{code} {code:java} 23:30:35 ____________________ perf_couchdb.test_FAB_3877_VaryNumTxs ______________ 23:30:35  23:30:35 self = <ledger_lte.perf_couchdb testMethod=test_FAB_3877_VaryNumTxs> 23:30:35  23:30:35     def test_FAB_3877_VaryNumTxs(self): 23:30:35         self.assertTrue(True) 23:30:35         ''' 23:30:35              In this Performance test, we observe the performance (time to 23:30:35              complete a set number of Ledger operations) of the Ledger component, 23:30:35              with couchdb as the state database. We vary the number of 23:30:35              transactions carried out. 23:30:35      23:30:35              Passing criteria: Underlying LTE test completed successfully with 23:30:35              exit code 0 23:30:35             ''' 23:30:35         logfile = open("output_VaryNumTxs_couchdb.log", "w") 23:30:35         returncode = subprocess.call( 23:30:35                 "./runbenchmarks.sh -f parameters_couchdb_daily_CI.sh varyNumTxs", 23:30:35                 shell=True, stderr=subprocess.STDOUT, stdout=logfile, 23:30:35                 cwd=tool_directory) 23:30:35         logfile.close() 23:30:35         self.assertEqual(returncode, 0, msg="varyNumTxs for CouchDB " 23:30:35                 "performance test failed. \nPlease check the logfile " 23:30:35 >               +logfile.name+" for more " "details.") 23:30:35 E       AssertionError: varyNumTxs for CouchDB performance test failed.  23:30:35 E       Please check the logfile output_VaryNumTxs_couchdb.log for more details. 23:30:35  23:30:35 ledger_lte.py:386: AssertionError 23:30:35 =================== 2 failed, 16 passed in 13576.66 seconds ==================== {code}  There has been no change in code which could have triggered this error. I am not giving this a high priority yet as this is a flake like many times.  *Build Log*  https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-test-daily-lte-release-1.4-x86_64/24/   ></description> </Issue>
