<Action id="25395" issue="17503" author="lovesh" type="comment" created="2017-06-05 17:06:42.0" updateauthor="lovesh" updated="2017-06-05 17:21:10.0"> <body><! CDATA    ~aleksey-roldugin  I see this error {code} return InsChgVotes(msg.viewNo, set()) TypeError: __new__() missing 1 required positional argument: 'last_ordered' {code}  Plenum's master has correct definition of *InsChgVotes*, see https://github.com/evernym/plenum/blob/master/plenum/server/models.py#L12 but Plenum's stable has incorrect definition of *InsChgVotes*, see https://github.com/evernym/plenum/blob/stable/plenum/server/models.py#L15. Or is it some node being on master codebase and some stable codebase  ></body> </Action>
<Action id="25397" issue="17503" author="aleksey-roldugin" type="comment" created="2017-06-05 17:27:53.0" updateauthor="aleksey-roldugin" updated="2017-06-05 17:27:53.0"> <body><! CDATA  ~lovesh  Packages version on all 6 nodes are the same: - python3-stp 0.1.10 amd64 - python3-ledger 0.2.14 amd64 - python3-plenum 0.3.15 amd64 - python3-sovrin-common 0.2.10 - sovrin-node 0.3.17   Machines stack was created from template on AWS and I selected rc CodeBase there.  ></body> </Action>
<Action id="25464" issue="17503" author="krw910" type="comment" body="I saw a similar issue with the RC build today. It is the same as last Friday where I added two nodes, the both catch up but don&apos;t receive any of the new transactions." created="2017-06-06 04:16:19.0" updateauthor="krw910" updated="2017-06-06 04:16:19.0"/>
<Action id="25469" issue="17503" author="krw910" type="comment" created="2017-06-06 06:23:50.0" updateauthor="krw910" updated="2017-06-06 06:23:50.0"> <body><! CDATA I narrowed down the issue to the following cause. I believe it is a transaction. I ran through the GST and added Node 5. I did not have any issues. On a hunch I ran through a test document we run just prior to adding the nodes which is the old ledger demo from January. It covers things like adding an abbreviated verkey  send NYM dest=4QxzWk3ajdnEA37NdNU5Kt verkey= ~8RBNqGxt6TsUL4uHQmpy4r  After running through the tests here I ran into the issue on Node 6. After it did a catch up it no longer accepted new transactions, but all the nodes that were in the pool when I ran through the ledger demo are just fine.  ></body> </Action>
<Action id="25476" issue="17503" author="lovesh" type="comment" body=" ~krw910  After suggestions from  ~ashcherbakov  creating a separate ticket regarding your last comment, INDY-155" created="2017-06-06 09:45:35.0" updateauthor="lovesh" updated="2017-06-06 09:45:35.0"/>
<Action id="25478" issue="17503" author="ashcherbakov" type="comment" body=" ~aleksey-roldugin   ~krw910  It looks like the root of the issue is a broken build. Let&apos;s check that the issue is not reproduced anymore on a new build." created="2017-06-06 09:49:44.0" updateauthor="ashcherbakov" updated="2017-06-06 09:49:44.0"/>
<Action id="25543" issue="17503" author="aleksey-roldugin" type="comment" created="2017-06-06 16:16:52.0" updateauthor="aleksey-roldugin" updated="2017-06-06 16:16:52.0"> <body><! CDATA  ~ashcherbakov ,  ~krw910  the issue in not reproduced on the build: - sovrin-node 0.3.19 - sovrin-client 0.3.20  ></body> </Action>
