<Action id="35772" issue="24716" author="sergey.minaev" type="comment" body="Sounds like internal `flush requests` called twice." created="2017-12-04 11:58:17.0" updateauthor="sergey.minaev" updated="2017-12-04 11:58:17.0"/>
<Action id="35773" issue="24716" author="dsurnin" type="comment" created="2017-12-04 11:59:23.0" updateauthor="dsurnin" updated="2017-12-04 11:59:23.0"> <body><! CDATA Some logs  2017-12-04 12:59:41,884 | DEBUG | authenticator.py ( 37) | stop | Stopping ZAP at b'inproc://zeromq.zap.1' 2017-12-04 12:59:41,884 | INFO | zstack.py ( 331) | stop | stack Alpha stopped 2017-12-04 12:59:41,884 | INFO | zstack.py ( 327) | stop | stack AlphaC closing its listener 2017-12-04 12:59:41,884 | DEBUG | zstack.py ( 360) | close | AlphaC starting to disconnect remotes 2017-12-04 12:59:41,884 | DEBUG | authenticator.py ( 37) | stop | Stopping ZAP at b'inproc://zeromq.zap.2' 2017-12-04 12:59:41,884 | INFO | zstack.py ( 331) | stop | stack AlphaC stopped 2017-12-04 12:59:41,884 | DEBUG | node.py ( 811) | closeAllKVStores | Alpha closing level dbs 2017-12-04 12:59:41,885 | DEBUG | motor.py ( 34) | set_status | Alpha changing status from stopping to stopped 2017-12-04 12:59:41,885 | INFO | looper.py ( 272) | shutdown | Looper shutting down now... 2017-12-04 12:59:41,885 | INFO | motor.py ( 63) | stop | Alpha is already stopped 2017-12-04 12:59:41,885 | INFO | motor.py ( 63) | stop | Beta is already stopped 2017-12-04 12:59:41,886 | INFO | motor.py ( 63) | stop | Gamma is already stopped 2017-12-04 12:59:41,886 | INFO | motor.py ( 63) | stop | Delta is already stopped 2017-12-04 12:59:41,886 | INFO | looper.py ( 279) | shutdown | Looper shut down in 0.000 seconds. INFO|indy::commands | src/commands/mod.rs:115 | WalletCommand command received INFO|wallet_command_executor | src/commands/wallet.rs:86 | Close command received INFO|indy::commands | src/commands/mod.rs:107 | PoolCommand command received INFO|pool_command_executor | src/commands/pool.rs:81 | Close command received INFO|poolpool_name_XaQMpuCPVTjqk | src/services/pool/mod.rs:924 | Drop started INFO|poolpool_name_XaQMpuCPVTjqk | src/services/pool/mod.rs:932 | Drop wait worker TRACE|indy::services::pool | src/services/pool/mod.rs:764 | zmq poll 1 TRACE|indy::services::pool | src/services/pool/mod.rs:781 | cmd   101, 120, 105, 116 ,  5, 0, 0, 0   TRACE|indy::services::pool | src/services/pool/mod.rs:715 | process_actions - Pool work terminated DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:367 | context dropped INFO|poolpool_name_XaQMpuCPVTjqk | src/services/pool/mod.rs:935 | Drop finished DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:460 | socket dropped DEBUG|zmq_pw |/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-pw-0.9.8/src/lib.rs:367 | context dropped INFO|indy::commands | src/commands/mod.rs:103 | LedgerCommand command received INFO|ledger_command_executor | src/commands/ledger.rs:142 | SubmitAck command received ERROR|indy::errors::indy | src/errors/indy.rs:63 | Casting error to ErrorCode: Pool work terminated INFO|indy::commands | src/commands/mod.rs:107 | PoolCommand command received INFO|pool_command_executor | src/commands/pool.rs:85 | CloseAck command received INFO|indy::commands | src/commands/mod.rs:103 | LedgerCommand command received INFO|ledger_command_executor | src/commands/ledger.rs:142 | SubmitAck command received thread '<unnamed>' panicked at 'Expect callback to process ack command', /checkout/src/libcore/option.rs:819:4 note: Run with `RUST_BACKTRACE=1` for a backtrace. =========================== 1 passed in 3.82 seconds =========================== 2017-12-04 12:59:41,923 | ERROR | base_events.py (1258) | default_exception_handler | Task exception was never retrieved future: <Task finished coro=<submit_request() done, defined at /home/tmh/evernym/indy-sdk/wrappers/python/indy/ledger.py:55> exception=IndyError(<ErrorCode.PoolLedgerTerminated: 302>,)> Traceback (most recent call last): File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step result = coro.throw(exc) File "/home/tmh/evernym/indy-sdk/wrappers/python/indy/ledger.py", line 81, in submit_request submit_request.cb) File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__ yield self # This tells Task to wait for completion. File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup future.result() File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result raise self._exception indy.error.IndyError: ErrorCode.PoolLedgerTerminated  ></body> </Action>
<Action id="38447" issue="24716" author="sergey.minaev" type="comment" created="2018-01-11 15:45:13.0" updateauthor="sergey.minaev" updated="2018-01-11 15:45:13.0"> <body><! CDATA PR fix: https://github.com/hyperledger/indy-sdk/pull/473 Reason: double flush pending request results in command thread failture Note: new integration test for this scenario has been added: indy_close_pool_ledger_works_for_pending_request  ></body> </Action>
