<Action id="37556" issue="26126" author="ozheregelya" type="comment" body="This problem actual only for master version." created="2017-12-17 17:33:24.0" updateauthor="ozheregelya" updated="2017-12-17 17:33:24.0"/>
<Action id="38347" issue="26126" author="ashcherbakov" type="comment" body="Please note that it needs to be fixed (if needed) in https://github.com/hyperledger/indy-node/tree/master/environment" created="2018-01-09 17:00:20.0" updateauthor="ashcherbakov" updated="2018-01-09 17:00:20.0"/>
<Action id="38348" issue="26126" author="ashcherbakov" type="comment" body="It&apos;s aleady fixed in the scope of INDY-1055, INDY-1060, INDY-1062" created="2018-01-09 17:04:56.0" updateauthor="ashcherbakov" updated="2018-01-09 17:04:56.0"/>
<Action id="38431" issue="26126" author="ashcherbakov" type="comment" body="Fixed in https://github.com/hyperledger/indy-node/pull/517" created="2018-01-11 14:02:56.0" updateauthor="ashcherbakov" updated="2018-01-11 14:02:56.0"/>
<Action id="38628" issue="26126" author="vladimirwork" type="comment" created="2018-01-15 13:39:18.0" updateauthor="vladimirwork" updated="2018-01-15 13:39:18.0"> <body><! CDATA Build Info: indy-node 1.2.270  Steps to Validate: 1. Build pool from stable branch with vagrant. 2. Build pool from master branch with vagrant. 3. Check shell output.  Actual Results: Pools from both branches were built successfully. There is no error with `/home/indy/.indy/indy_config.py`.  ></body> </Action>
