<Issue id="41368" key="INDY-2180" number="2180" project="10303" reporter="vladimirwork" assignee="ashcherbakov" creator="vladimirwork" type="10004" summary="One node can&apos;t catch up" priority="3" resolution="10000" status="10001" created="2019-07-23 13:43:25.0" updated="2019-07-24 09:45:17.0" resolutiondate="2019-07-24 09:45:17.0" votes="0" watches="2" workflowId="54375"> <description><! CDATA Build Info: indy-node 1.9.0~dev1036  Steps to Reproduce: https://github.com/hyperledger/indy-test-automation/blob/163a56b21c5df792b26595d00211047b16311baa/system/indy-node-tests/TestAuditSuite.py#L13  Actual Results: 1st node can't catch up after stopping and starting.  Additional Info: This issue reproduces intermittently (1..2 times from 10 attempts).  ></description> </Issue>
