<Action id="18702" issue="12558" author="jamesyu" type="comment" created="2016-08-28 09:50:23.0" updateauthor="jamesyu" updated="2016-08-28 09:50:23.0"> <body><! CDATA Traffic seems to go through, however the following provision give the following error  ==> default: protoc --proto_path=/opt/gopath/src/github.com/hyperledger/fabric/consensus/pbft --go_out=plugins=grpc:/opt/gopath/src/github.com/hyperledger/fabric/consensus/pbft /opt/gopath/src/github.com/hyperledger/fabric/consensus/pbft/*.proto {color:#d04437}==> default: protoc-gen-go ==> default: : program not found or is not executable ==> default: --go_out ==> default: :  ==> default: protoc-gen-go: Plugin failed with status code 1. ==> default: make:  ==> default: ***  consensus/pbft/messages.pb.go  Error 1{color} The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.   ></body> </Action>
<Action id="18835" issue="12558" author="greg.haskins" type="comment" body="Is this reproducible?  It seems to be working fine for me as of yesterday.  I will try again today with the latest." created="2016-09-09 16:55:22.0" updateauthor="greg.haskins" updated="2016-09-09 16:55:22.0"/>
<Action id="18837" issue="12558" author="greg.haskins" type="comment" body="I think the issue that precipitated the protoc-gen-go has been reverted.  I am not able to reproduce the atlas access issue with v0.0.11 but I suspect it was environmental to the user.  I confirmed that a fresh vagrant destroy/up works as expected on f6403a8.  Recommend closing for now.  Can be reopened if persists." created="2016-09-09 17:40:12.0" updateauthor="greg.haskins" updated="2016-09-09 17:40:12.0"/>
